### PR TITLE
Features signup and Login

### PR DESCRIPTION
**Pull request by iamatinad**

### CODE REVIEW

**Comment by emmanuelAkpe** [comment]
Great job
kindly send the pr into the development branch @iamatinad

**Comment by iamatinad** [comment]
@emmanuelAkpe PR sent to dev

**Review by emmanuelAkpe — CHANGES_REQUESTED** [review]
great job. It looks beautiful
Kindly check the following changes

1. The otp page should be the last page in the registration process.
currently, the otp comes before the last page

2. On the otp page, when a user enters a value, the focus  should automatically move onto the next otp box
3. when i click on the signup in the login page, it doesnt lead back to signup page

**Comment by iamatinad** [comment]
@emmanuelAkpe please the requested have been implemented.

**Review by emmanuelAkpe — APPROVED** [review]

**Pull request merged**
