### PR TITLE
created the features component

### PR DESCRIPTION
**Pull request by JoanaQuadzie**

### CODE REVIEW

**Comment by emmanuelAkpe** [comment]
@JoanaQuadzie , kindly research on likey questions and add it to the FAQ.
Do not use any dummy or lorem ips

**Review by emmanuelAkpe — CHANGES_REQUESTED** [review]
@JoanaQuadzie there has been many changes in the Home
kindly fetch from upstream and make the neccessary adjustments before you push for merge

**Comment by emmanuelAkpe** [comment]
Put the Faqs in their separate component
the features too
and render the components in the Home 

Do not write everything in the Home like you have done

**Comment by JoanaQuadzie** [comment]
Noted sir
Will do that

**Review by emmanuelAkpe — APPROVED** [review]

**Pull request merged**
