### PR TITLE
hero section  added

### PR DESCRIPTION
**Pull request by iamatinad**

### CODE REVIEW

**Comment by emmanuelAkpe** [comment]
kindly send the pr to the development branch @iamatinad

**Comment by iamatinad** [comment]
@emmanuelAkpe PR sent to dev

**Review by emmanuelAkpe — CHANGES_REQUESTED** [review]
The  App.jsx is not in alignment with the routes setup causing a conflict 
Make sure you fetch from the upstream development branch to get the current changes
@iamatinad

**Comment by iamatinad** [comment]
@emmanuelAkpe  well noted new PR sent for hero section

**Pull request closed without merging**
